### ISSUE TITLE
Can't apply migrations after installing the module

### ISSUE THREAD

**Issue by PierreMesure** [mainio/decidim-module-accountability_simple#1]
Hi Antti,

I installed your module a few weeks ago to try it out, haven't used its functionalities yet.

But I was trying to reset my local development database the other day and I now had this error when doing a `db:migrate`:

```
== 20190213010997 AddActionLog: migrating =====================================
-- create_table(:decidim_action_logs, {})
   -> 0.0698s
-- add_index(:decidim_action_logs, :created_at)
   -> 0.0048s
== 20190213010997 AddActionLog: migrated (0.0747s) ============================

== 20190213010998 FixReferenceForAllResources: migrating ======================
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "decidim_accountability_results" does not exist
LINE 1: SELECT  "decidim_accountability_results".* FROM "decidim_acc...
                                                        ^
: SELECT  "decidim_accountability_results".* FROM "decidim_accountability_results" ORDER BY "decidim_accountability_results"."id" ASC LIMIT $1
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:677:in `async_prepare'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:677:in `block in prepare_statement'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:672:in `prepare_statement'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:617:in `exec_cache'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:600:in `execute_and_clear'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:81:in `exec_query'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:482:in `select_prepared'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:68:in `select_all'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/query_cache.rb:106:in `select_all'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/querying.rb:41:in `find_by_sql'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/relation.rb:560:in `block in exec_queries'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/relation.rb:581:in `block in skip_query_cache_if_necessary'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/query_cache.rb:78:in `uncached'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/query_cache.rb:21:in `uncached'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/relation/delegation.rb:114:in `public_send'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/relation/delegation.rb:114:in `block in method_missing'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/relation.rb:281:in `scoping'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/relation/delegation.rb:114:in `method_missing'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/relation.rb:580:in `skip_query_cache_if_necessary'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/relation.rb:547:in `exec_queries'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/relation.rb:422:in `load'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/relation.rb:200:in `records'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/relation/batches.rb:224:in `block in in_batches'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/relation/batches.rb:222:in `loop'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/relation/batches.rb:222:in `in_batches'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/relation/batches.rb:135:in `find_in_batches'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/relation/batches.rb:69:in `find_each'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/querying.rb:11:in `find_each'
/Users/Pierre/Code/digidemlab/decidim-sweden/db/migrate/20190213010998_fix_reference_for_all_resources.decidim.rb:9:in `block in up'
/Users/Pierre/Code/digidemlab/decidim-sweden/db/migrate/20190213010998_fix_reference_for_all_resources.decidim.rb:8:in `each'
/Users/Pierre/Code/digidemlab/decidim-sweden/db/migrate/20190213010998_fix_reference_for_all_resources.decidim.rb:8:in `up'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:817:in `exec_migration'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:797:in `block in migrate'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:796:in `migrate'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:977:in `migrate'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1343:in `block in ddl_transaction'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:212:in `transaction'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1343:in `ddl_transaction'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1262:in `each'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1210:in `block in migrate'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1210:in `migrate'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1036:in `up'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1011:in `migrate'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.4/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <main>'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.4/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.4/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.4/lib/rails/command.rb:48:in `invoke'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.4/lib/rails/commands.rb:18:in `<main>'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/Users/Pierre/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
bin/rails:4:in `<main>'
```

Is this something you experienced? I didn't have any problem upgrading my setup to include your module's migrations the first time, it seems it's only when applying all the migrations again.

To fix it, I deactivated the module and deleted the migration files manually.

**Comment by ahukkanen** [comment]
This is not an issue with this module. This was a core bug.

We have bumped into the same issue and it has been already fixed in core (version 0.24+):
https://github.com/decidim/decidim/pull/7205
